export const APP_EVENTS = {
  changePaginationPage: 'changePaginationPage',
  changeCategoryMenu: 'changeCategoryMenu',
  storage: 'storage',
  changeRoute: 'change-route',
  cartcounter: 'cartcounter',
  changeTab: 'changetab',
  createCategory: 'createCategory',
  createProduct: 'createProduct',
  createSales: 'createSales',
  signUp: 'signUp',
  signIn: 'signIn',
  authorizeUser: 'authorizeUser',
  tata: 'tata',
};
