export const APP_ROUTES = {
  main: '/',
  mainPage: '/#it-mainpage',
  menuPage: '/#menu_page',
  aboutUsPage: '/#about_us_page',
  galleryPage: '/#gallery_page',
  salesPage: '/#sales_page',
  contactsPage: '/#contacts_page',
  signUp: '/sign-up',
  signIn: '/sign-in',
  signOut: '/sign-out',
  adminPage: '/admin-page',
  cartPage: '/cart-page',
  errorPage: '/error-page',
};
